import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn, revalidateTime } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider"

const inter = Inter({ subsets: ["latin"] });

export const revalidate = revalidateTime;

export const metadata: Metadata = {
  title: "MOHAMMED",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={cn("relative text-muted-foreground overflow-x-hidden", inter.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >

          {children}
          
        </ThemeProvider>
      </body>
    </html>
  );
}
